id: ecb3451cd018458e9717f78c0251e4ae
initial_creation_type: ocr
source_metadata:
  volumes:
    5ad4a55db5a646e8bf512da8e0edf334:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: ''
      total_pages: 2107
      volume_number: 11
